# Generated by Django 5.2.7 on 2025-11-05 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('qs_rating_top', models.IntegerField()),
                ('qs_rating_bottom', models.IntegerField()),
                ('web_pages', models.URLField()),
                ('status', models.CharField(max_length=255)),
                ('continent', models.CharField(choices=[('Africa', 'África'), ('America', 'América'), ('Asia', 'Asia'), ('Europe', 'Europa'), ('Oceania', 'Oceania')], max_length=50)),
                ('visits_count', models.IntegerField(default=0, help_text='Número de veces que se ha visto la universidad')),
                ('faculties', models.ManyToManyField(blank=True, help_text='Facultades con las que esta universidad tiene convenio', related_name='universities', to='universities.faculty')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=511)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('social_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('academic_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('place_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='universities.university')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='university_photos/')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='universities.university')),
            ],
            options={
                'verbose_name': 'Foto de Universidad',
                'verbose_name_plural': 'Fotos de Universidades',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de deseos',
                'verbose_name_plural': 'Listas de deseos',
            },
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['country'], name='universitie_country_a1a531_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['continent'], name='universitie_contine_d3c4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['qs_rating_top'], name='universitie_qs_rati_b0db30_idx'),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.CheckConstraint(condition=models.Q(('qs_rating_bottom__gte', models.F('qs_rating_top'))), name='qs_rating_bottom_gte_qs_rating_top'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'university'], name='universitie_user_id_f1fd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-start_date'], name='universitie_start_d_58b369_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'university'), name='unique_user_university_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='review_end_after_start'),
        ),
    ]
