# Generated by Django 5.2.7 on 2025-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='faculties',
            field=models.ManyToManyField(blank=True, help_text='Facultades con las que esta universidad tiene convenio', related_name='universities', to='universities.faculty'),
        ),
    ]
