# Generated by Django 5.2.7 on 2025-10-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='faculties',
            field=models.ManyToManyField(blank=True, help_text='Facultades con las que esta universidad tiene convenio', related_name='universities', to='universities.faculty'),
        ),
    ]
