# Generated by Django 5.2.7 on 2025-11-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, max_length=511, null=True),
        ),
    ]
