# Generated by Django 5.2.7 on 2025-10-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_remove_wishlist_unique_wishlist_per_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='university_photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='university',
            name='continent',
            field=models.CharField(choices=[('Africa', 'África'), ('America', 'América'), ('Asia', 'Asia'), ('Europe', 'Europa'), ('Oceania', 'Oceania')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.CheckConstraint(condition=models.Q(('qs_rating_bottom__gte', models.F('qs_rating_top'))), name='qs_rating_bottom_gte_qs_rating_top'),
        ),
        migrations.AddField(
            model_name='photosuniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='universities.university'),
        ),
    ]
