# Generated by Django 5.2.7 on 2025-11-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosuniversity',
            name='university_name_linker',
            field=models.CharField(blank=True, db_index=True, help_text='Usado internamente para re-enlazar fotos si las universidades se recargan.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photosuniversity',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='universities.university'),
        ),
    ]
