# Generated by Django 5.2.7 on 2025-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_faculties'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['country'], name='universitie_country_a1a531_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['continent'], name='universitie_contine_d3c4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['qs_rating_top'], name='universitie_qs_rati_b0db30_idx'),
        ),
    ]
