# Generated by Django 5.2.7 on 2025-10-27 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_photosuniversity_alter_university_continent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photosuniversity',
            options={'verbose_name': 'Foto de Universidad', 'verbose_name_plural': 'Fotos de Universidades'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Universidad', 'verbose_name_plural': 'Universidades'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Lista de deseos', 'verbose_name_plural': 'Listas de deseos'},
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_university_wishlist',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='universities.university'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'university'], name='universitie_user_id_f1fd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-start_date'], name='universitie_start_d_58b369_idx'),
        ),
    ]
