# Generated by Django 5.2.9 on 2026-02-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
