# Generated by Django 5.2.7 on 2025-10-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_photosuniversity_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
