# Generated by Django 5.2.9 on 2026-02-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_university_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
